- Dockerfile
- compose.yaml
- requirements.txt
- uwsgi.ini
- add non-root user in Dockerfile
- add uwsgi.ini
- replace `lando runserver` with `uwsgi` -
> docker: configure uwsgi server for application (bug 1868134)

- nginx/nginx.conf
- src/lando/settings.py
- also add lando.test to (default) trusted csrf origins
> nginx: add http -> https redirect (bug 1899391)

- src/lando/jinja.py
- src/lando/ui/jinja2/errorhandlers/revisions_404.html
- src/lando/ui/jinja2/partials/layout.html
- src/lando/ui/jinja2/partials/navbar.html
- src/lando/ui/jinja2/stack/stack.html
- reimplement user_has_phabricator_token
- reimplement user_is_authenticated (originally is_user_authenticated)
> jinja: reimplement auth template variables (bug 1908137)

- Dockerfile
- compose.yaml
- nginx/nginx.conf
- fix app user parameters in Dockerfile
- update media volume in compose file
- remove unneeded media alias in nginx config
> misc: update Docker related files (bug 1909957)

- src/lando/main/admin.py
- src/lando/main/management/commands/landing_worker.py
- src/lando/main/models/__init__.py
- src/lando/main/models/base.py
- src/lando/main/models/repo.py
- src/lando/main/models/worker.py
- src/lando/tests/test_formatting.py
- src/lando/utils/management/commands/format.py
- src/lando/utils/management/commands/setup_dev.py
- src/lando/utils/management/commands/start_celery_worker.py
- move Repo model to its own module
- move Worker model to its own module
- update imports
> models: move Repo and Worker models to own modules (bug 1913168)

- src/lando/settings.py
- Fetch MEDIA_ROOT from environment
- Remove empty DIRS list in Jinja2 template backend
- Update default value for DEFAULT_DB_HOST
- Differentiate domain from base URL for OIDC
- Update various OIDC variables
- Add login and logout redirect URLs
- Add BUGZILLA_URL variable
> settings: update various variables (bug 1915240)

- src/lando/ui/legacy/revisions.py
NOTE: This is an intermediate commit to facilitate reviewing the rest of the implementation code related to this bug. Ignore any missing imports or other issues related to the uncommenting of this code.
> ui: uncomment various sections from ui.legacy.revisions (bug 1876838)

- src/lando/ui/jinja2/stack/stack.html
- src/lando/ui/legacy/revisions.py
- src/lando/urls.py
- fix jinja template styling
- temporarily comment out uplift related code
- implement changes to the view to make it work with new functionality
- update urls
> ui: port stack page and supporting functionality (bug 1876838)

- src/lando/utils/management/commands/setup_dev.py
- add method that creates or updates admin user on local environment
- split handling of functionality into individual methods
> commands: update setup_dev to add admin user (bug 1917078)

- Makefile
- README.md
- compose.yaml
- src/lando/utils/management/commands/create_environment_repos.py
- src/lando/utils/management/commands/setup_dev.py
- run migrations
- ensure local repos exists
- ensure local workers exists
- ensure admin user exists
- update README
- update Makefile
> commands: improve local development commands (bug 1917079)

- src/lando/static_src/legacy/js/main.js
- src/lando/ui/jinja2/partials/layout.html
- add missing script to layout.html
- clean up and sort things
> ui: add Stack.js to scripts (bug 1920153)

- src/lando/__init__.py
- src/lando/jinja.py
- src/lando/manage.py
- src/lando/settings.py
- src/lando/test_settings.py
- src/lando/ui/admin.py
- src/lando/ui/legacy/api.py
- src/lando/ui/legacy/forms.py
- src/lando/ui/legacy/pages.py
- src/lando/ui/legacy/revisions.py
- src/lando/ui/legacy/stacks.py
- src/lando/ui/legacy/usersettings.py
- src/lando/ui/models.py
- src/lando/ui/tests/conftest.py
- src/lando/ui/tests/test_forms.py
- src/lando/ui/tests/test_landoapi.py
- src/lando/ui/tests/test_py3_codequality.py
- src/lando/ui/tests/test_stacks.py
- src/lando/ui/tests/test_template_helpers.py
- src/lando/ui/tests/test_usersettings.py
- src/lando/urls.py
- update LINT_PATHS
- run `lando format`
> settings: update lint paths to be more comprehensive (bug 1918236)

- compose.yaml
- uwsgi.ini
- add local, development, staging, and production configs
> uwsgi: add environment specific configs (bug 1904616)

- src/lando/middleware.py
- add *.googleapis.com
- fix inline styles for debug pages
- remove unneeded hosts (cloudfront.net and googleusercontent.com)
> middleware: various CSP fixes (bug 1934038)

- src/lando/middleware.py
- update font-src and style-src entires with correct values
> middleware: more CSP fixes (bug 1934091)

- src/lando/main/management/commands/start_landing_worker.py
- add separate method to check for unsupported repos
- add retry capability to landing work repo cloning
- raise CommandError if repo is not cloned successfully
> start_landing_worker: improve repo cloning (bug 1941015)

- src/lando/api/tests/test_hooks.py
- src/lando/api/tests/test_landings.py
- src/lando/api/tests/test_transplants.py
- src/lando/api/tests/test_uplift.py
- tests are passing and should have been unmarked some time ago
> tests: cleanup tests (bug 1944851)

- src/lando/utils/apps.py
See also: https://github.com/mozilla-it/webservices-infra/pull/3887/files
> apps: run phabricator_check on deployments only (bug 1917294)

- src/lando/main/models/repo.py
- src/lando/main/scm/abstract_scm.py
- src/lando/main/scm/git.py
- src/lando/main/scm/hg.py
- src/lando/main/tests/test_models.py
(cherry picked from commit ff0dbd3c06af3830975e3f3e70f6949b9c964938)
This commit disappeared in a previous merge.
> repo: pass default_branch to SCM if set (bug 1951843) (#229)

- Dockerfile
See https://github.com/pypa/wheel/issues/662.
> Dockerfile: upgrade setuptools (bug 1959332)

- src/lando/api/tests/test_phabricator_client.py
- src/lando/utils/phabricator.py
- add method to aggregate result data from multiple requests
> phabricator: get_conduit_result_data implementation (bug 1953929)

- src/lando/main/scm/git.py
- src/lando/main/tests/test_git.py
Add calls to `git am --abort` before and after running `git am` to
clean up any failed attempts to apply patches to the repo.
> git: cleanup after failed `git am` in `apply_patch_bytes` (Bug 1974047)

- src/lando/main/models/configuration.py
- src/lando/middleware.py
- src/lando/settings.py
- add PROFILING_ENABLED configuration variable
- add cProfileMiddleware
> middleware: add cProfileMiddleware (bug 1958263)

- src/lando/main/models/repo.py
- defaulting to SSH is no longer needed and can be manually set
- add default branch (main) if this is a git repo
- do some clean up and add comments
> repo: do not default to SSH for pull path (bug 1958211)

- pyproject.toml
- requirements.txt
- remove constraint on pip package
- run make upgrade-requirements
- see #454 which fixes the underlying issue
> requirements: remove constraint on pip (bug 1975463)

- src/lando/api/legacy/workers/automation_worker.py
- src/lando/api/legacy/workers/base.py
- src/lando/api/legacy/workers/landing_worker.py
Add a `Worker.update_repo` method which calls `scm.update_repo`
with common error handling and job status transitions.
> workers: add a worker-level `update_repo` method (Bug 1989299)
