mozilla-conduit/lando

- requirements.txt
- src/lando/jinja2.py
- src/lando/settings.py
- add jinja2 to requirements
- update settings to pick up jinja2 templates
- add basic jinja2 environment to lando
> settings: add jinja2 support (bug 1873071)

- Dockerfile
- src/lando/api/legacy/api/landing_jobs.py
- src/lando/api/legacy/api/stacks.py
- src/lando/api/legacy/api/transplants.py
- src/lando/api/legacy/api/try_push.py
- src/lando/api/legacy/auth.py
- src/lando/api/legacy/hg.py
- src/lando/api/legacy/transplants.py
- src/lando/api/tests/conftest.py
- src/lando/api/tests/test_decorators.py
- src/lando/api/tests/test_landings.py
- src/lando/api/tests/test_revisions.py
- src/lando/api/tests/test_stacks.py
- src/lando/api/tests/test_transplants.py
- src/lando/api/tests/test_try.py
- src/lando/main/models/base.py
- src/lando/main/models/landing_job.py
- src/lando/main/support.py
- src/lando/settings.py
- src/lando/test_settings.py
- src/lando/utils/management/commands/tests.py
No implementation changes in this PR, however there is the addition of proxy_client, which will likely be used by any future commits from the legacy repos that contain changes to API tests, until that functionality is fully ported.
Tests that have been skipped will be readded in a future PR with fixes for those tests. At this point, CI should be passing and future PRs should continue this trend.
- add proxy client to get tests to pass with minimal changes
- reorder some test arguments (e.g., project fixtures)
- make temporary changes in conftest until test env vars are fixed
- remove suppress failure (cache) in auth module (bug 1870285)
- fix queryset/db issues (leftover from bug 1886854)
- add a couple more proxy endpoints to proxy client
- update support shims to better accommodate …
> tests: more fixes to tests (bug 1887042)

- .gitignore
- compose.yaml
- generate_version_file.py
- pyproject.toml
- requirements.txt
- src/lando/tests/test_formatting.py
- src/lando/tests/test_version.py
- src/lando/utils/management/commands/generate_version_file.py
`setuptools_scm` is meant to generate the `_version.py` file when building a wheel for a project, but we can use the same code to explicitly generate it when we 'build' using the Dockerfile.
The 'version' text generated is the `git tag` with the commit hash appended. The version file is not committed to VCS.
> version: Use `setuptools_scm` to generate the version (bug 1867133)

- src/lando/urls.py
Without this change, the warning presented is:
`(urls.W002) Your URL pattern '/D<int:revision_id>/' has a route beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.`
> lando: Fix url pattern warning (bug 1870695)

- Dockerfile
- ruff.toml
- src/lando/api/legacy/api/uplift.py
- src/lando/api/legacy/bmo.py
- src/lando/api/legacy/cache.py
- src/lando/api/legacy/celery.py
- src/lando/api/legacy/decorators.py
- src/lando/api/legacy/phabricator.py
- src/lando/api/legacy/phabricator_patch.py
- src/lando/api/legacy/repos.py
- src/lando/api/legacy/sentry.py
- src/lando/api/legacy/smtp.py
- src/lando/api/legacy/tasks.py
- src/lando/api/legacy/treestatus.py
- src/lando/api/legacy/ui.py
- src/lando/api/legacy/uplift.py
- src/lando/api/legacy/workers/landing_worker.py
- src/lando/api/tests/conftest.py
- src/lando/api/tests/test_landing_job.py
- src/lando/api/tests/test_try.py
- src/lando/main/admin.py
- src/lando/main/models/__init__.py
- src/lando/main/models/base.py
- src/lando/tests/test_formatting.py
- src/lando/utils/management/commands/tests.py
Also resolved the following warnings:
- `error: Failed to initialize cache at /.ruff_cache: Permission denied (os error 13)` by creating the directory and taking ownership of it in the Dockerfile.
- `warning: The top-level linter settings are deprecated in favour of their counterparts in the lint section. Please update the following options in code/ruff.toml:  - 'ignore' -> lint.ignore'  - 'select' -> 'lint.select'  - 'isort' -> 'lint.isort'` by making the suggested changes in the `ruff.toml`.
`test_ruff` and `test_black` are now both enabled and passing.
> formatting: Fix code style and code style tests (bug 1897434)

- Makefile
I also shifted the `help` output to follow the same style even with the longer `migrations` word in the list now.
> makefile: Add `lando makemigrations` command to the Makefile (bug 1897551)

- Makefile
We need to quote the calls to the `docker` and `docker-compose` executables, since their absolute paths can contain spaces on Windows.
> makefile: Fix `make help` on Windows (bug 1897553)

- src/lando/static_src/TEMPORARY_FILE
Added a temporary file to ensure the `src\lando\static_src` directory exists to remove the `STATICFILES_DIRS` warning.
> lando: Fix `STATICFILES_DIRS` warning (bug 1897550)

- compose.yaml
The `--clear` argument will ensure all stale static files are deleted.
> static_files: clear `STATIC_ROOT` on `collectstatic` call (bug 1903648)

- src/lando/api/legacy/api/stacks.py
- src/lando/api/legacy/api/transplants.py
- src/lando/api/legacy/api/uplift.py
- src/lando/api/legacy/hooks.py
- src/lando/api/legacy/projects.py
- src/lando/api/legacy/reviews.py
- src/lando/api/legacy/revisions.py
- src/lando/api/legacy/stacks.py
- src/lando/api/legacy/transactions.py
- src/lando/api/legacy/transplants.py
- src/lando/api/legacy/uplift.py
- src/lando/api/legacy/users.py
- src/lando/api/tests/conftest.py
- src/lando/api/tests/mocks.py
- src/lando/api/tests/test_hooks.py
- src/lando/api/tests/test_phabricator.py
- src/lando/api/tests/test_phabricator_client.py
- src/lando/api/tests/test_reviews.py
- src/lando/api/tests/test_revisions.py
- src/lando/api/tests/test_stacks.py
- src/lando/api/tests/test_tasks.py
- src/lando/api/tests/test_transplants.py
- src/lando/api/tests/test_uplift.py
- src/lando/main/auth.py
- src/lando/main/tests/__init__.py
- src/lando/utils/apps.py
- src/lando/utils/phabricator.py
- src/lando/utils/tasks.py
- add phabricator check to replace legacy health check
- check unprivileged and admin keys for validity
- remove phabricator subsystem
- move relevant functionality to lando.utils.phabricator
- update imports
- add get_phabricator_client method
> utils: phabricator client changes (bug 1915633)

- src/lando/main/logging.py
- src/lando/settings.py
- move legacy logging config to new platform
- remove unneeded loggers (flask, werkzeug)
- update django logger to match rest of the config
- convert field values to string to ensure JSON serializability
- only use custom logging on remote environments
> logging: port legacy logging functionality (bug 1867613)

- src/lando/main/sentry.py
This fixes a race where the version file generator cannot run because the version file is missing.
> sentry: only load version information for remote interaction (bug 1920808)

- src/lando/main/models/profile.py
- check for existence of CLAIM_GROUPS_KEY (bug 1927153)
- exclude "name" from filtered fields (bug 1927152)
> profile: userinfo filtering fixes

- src/lando/api/legacy/hooks.py
- src/lando/api/tests/test_hooks.py
- src/lando/middleware.py
- src/lando/settings.py
- src/lando/ui/tests/test_csp.py
- port app wide headers hook (from legacy UI and API)
- re-enable previously skipped test (bug 1926964)
- remove some legacy code
- add failing test to account for future functionality
> middleware: add response headers middleware (bug 1927148)

- Makefile
- src/lando/utils/management/commands/tests.py
This allows to run only a subset of the tests.
> commands.test: add support for -k option

- .gitignore
We generate this file as part of code coverage reports in
the test suite, it should be ignored by Git.
> git: add `.coverage` to `.gitignore`

- src/lando/api/legacy/spec/swagger.yml
- src/lando/api/legacy/workers/landing_worker.py
- src/lando/api/tests/test_landings.py
- src/lando/main/models/landing_job.py
- src/lando/main/scm/abstract_scm.py
- src/lando/main/scm/hg.py
- src/lando/ui/jinja2/stack/partials/timeline.html
Add test coverage for good measure (and remove the never-used `job.error_breakdown["content"]`).
Much better!
Before:
After:
> landing_worker: fix handling of merge conflicts (bug 1938162) (bug 1935549)

- src/lando/api/legacy/api/__init__.py
- src/lando/api/legacy/api/uplift.py
- src/lando/api/legacy/uplift.py
- src/lando/ui/jinja2/stack/stack.html
- src/lando/ui/legacy/forms.py
- src/lando/ui/legacy/revisions.py
- src/lando/urls.py
- port existing uplift functionality
- adapt form to use new fields
- update endpoints and connect them to legacy api
Note: This ports an early version of uplift functionality that was moved over as part of the initial repo migration.
> uplift: port functionality (bug 1915695)

- src/lando/api/legacy/api/landing_jobs.py
- src/lando/api/tests/test_hooks.py
- src/lando/api/tests/test_landing_job.py
- src/lando/static_src/legacy/js/components/Timeline.js
- fix landing job cancel tests
- remove unneeded phabricator exception test
- fix bug in JS code that called endpoint without trailing slash
> tests: handle skipped tests (bug 1897504)

- src/lando/api/tests/conftest.py
- src/lando/conftest.py
Create a global `conftest.py` for fixtures to be used across apps. Move test fixtures that will be used in the headless API into the global conftest.
> tests: create a global `conftest.py` (Bug 1942851)

- src/lando/utils/management/commands/create_environment_repos.py
- also add newest ESR repo
- improve logging
> create_environment_repos: allow running command on prod (bug 1944072)

- src/lando/utils/management/commands/create_environment_repos.py
This was causing `AttributeError: 'IntegrityError' object has no attribute 'endswith'`.
> create_environment_repos: fix error log

- src/lando/api/tests/conftest.py
Since the default value is `None`, `overrides` is not always `dict`.
> conftest: mark `overrides` as possibly being `None`

- src/lando/api/legacy/workers/landing_worker.py
The "enabled repos" line in the debug logging statement is missing
the `f` prefix to mark it as an f-string.
> landing_worker: mark log message as an f-string

- src/lando/api/legacy/workers/landing_worker.py
During the LandoAPI repo merge, the autoformatting changes from
bug 1924891 were not correctly merged into the new repo. Port
the changes so only the verified subset of linters run in
new Lando.
> landing_worker: port autoformatting changes from bug 1924891 (Bug 1954781)

- src/lando/api/legacy/workers/landing_worker.py
Now that `mach format` runs `eslint` as a formatter without fixes,
we can use `mach format` to autoformat patches, removing the need
to maintain our own list of valid formatters.
> landing_worker: use `mach format` for autoformatting (Bug 1807712)

- src/lando/utils/management/commands/create_environment_repos.py
This script will now only be executable on non-production environments, e.g. to restore repo configuration.
> commands: remove production repos from repos command (bug 1955596)

- src/lando/static_src/legacy/css/pages/StackPage.scss
This lets the browser position the checkbox to the baseline rather than manually positioning it.
> pages: fix misaligned warning checkboxes

- src/lando/main/tests/test_models.py
- src/lando/pushlog/tests/conftest.py
Set UTC timezone when calling `datetime.now`. This silences warnings
about using a naive timestamp when the ORM uses timestamped datetimes.
> tests: set UTC timezone in `datetime.now` calls (Bug 1958317)

- src/lando/headless_api/api.py
- src/lando/headless_api/tests/test_automation_api.py
Add a simple endpoint to retrieve repo status given
a Phabricator short name.
> automation-api: implement `repoinfo` endpoint (Bug 1961077)

- src/lando/headless_api/api.py
`target` is marked as `str | None`, however since there is no default
value set, it is required in the request body. Set `None` as the default
value to the field can be omitted.
> automation-actions: set a default for `target` so it is optional (Bug 1962171)

- src/lando/headless_api/api.py
- src/lando/headless_api/tests/test_automation_api.py
Using `.dict()` converts the Pydantic models to a `dict`, but does
not properly convert Python types like `datetime` into a JSON
serializeable format. Switch to using `.model_dump(mode="json")`
which does the correct conversion.
> headless_api: store Pydantic models in DB using `.model_dump(mode="json")` (Bug 1962191)

- src/lando/jinja.py
- src/lando/ui/tests/test_template_helpers.py
- remove ".git" suffix if it exists in linkify_transplant_details
- make test more explicit
> jinja: remove .git suffix from URL if needed (bug 1961845)

- src/lando/api/legacy/api/transplants.py
- src/lando/api/tests/test_phabricator_client.py
- src/lando/utils/phabricator.py
- ignore limit when calling call_conduit
- return data based on original limit after collating
For queries that are expected to return greater than 100 results
setting the limit does not make sense as Phabricator limits results
to 100 anyway. So in those cases, we ignore the limit set, and then
discard any excess records. This is done for compatibility at this
time since various methods currently set a limit.
> phabricator: support limits when collating (bug 1957891)

- src/lando/utils/management/commands/create_environment_repos.py
Remove the already-created repos and only create the `main` repo in
`create_environment_repos`.
> create_environment_repos: create `firefox-main` repo in Lando (Bug 1963410)

- src/lando/api/legacy/uplift.py
- Phabricator expects this value to be set for git commits
- Mercurial commits that are copied over do not include this value
See [bug 1963689](https://bugzilla.mozilla.org/show_bug.cgi?id=1963689) for full fix.
> uplift: pass empty tree hash when creating diff (bug 1963679)

- src/lando/headless_api/tests/test_automation_api.py
- src/lando/main/scm/git.py
- src/lando/main/tests/test_git.py
Currently we have been forcing `--no-ff` merges in `GitSCM.merge_onto`.
When possible, we want to allow fast-foward merges to take place.
Update `merge_onto` to only enforce `--no-ff` when using a merge
strategy, since in that case the strategy will be avoided when
a fast-foward is possible, so the strategy will be ignored.
> git: only force a `--no-ff` merge when strategy is explicitly passed (Bug 1963699)

- src/lando/api/legacy/workers/landing_worker.py
Use `repo.default_branch` as the repo name for Bugzilla
updates on uplift. In the new unified Git repo model,
the branch names map to the expected values in BMO
for tracking flags.
> uplifts: use `repo.default_branch` as repo name for uplifts (Bug 1963870)

- src/lando/utils/management/commands/create_environment_repos.py
This will allow RelEng to have a set of dedicated repositories that we can write to as part of Try tasks to verify our own automation, that we'll also be able to force push to/reset as needed.
We explicitly do _not_ want to sync these back to hg to avoid any complications when we force push to them.
I ended up using scm level 1 for these, since they are Try-oriented repositories.
> create_environment_repo: add releng staging branches (bug 1964674)

- src/lando/utils/management/commands/create_environment_repos.py
These repos are no longer needed in the script, since it has already been run.
> create_environment_repos: remove prod repos from script (bug 1959193)

- src/lando/api/legacy/hgexports.py
- src/lando/api/tests/test_hgexports.py
- work around issue with `email.message.get_content` corrupting message with unexpected characters
- add headers to test patch to make sure the correct code paths are triggered in the test
> hgexports: use bytes when initializing email message (bug 1969532)

- src/lando/main/scm/git.py
- src/lando/main/tests/test_git.py
When applying patches to Git repos in Lando, we apply the patch
with `git apply` and then add the new files to the index with
`git add`. Using this strategy means the `.gitignore` file in
the repo is respected and files that are ignored will not be
added to the patch. Add `-f` to the `git add` call so ignored
files are also included in the index before committing. This
aligns with how `HgSCM.apply_patch` works as we directly apply
patches without considering `.hgignore`.
> git: add `-f` to `git add` call in `apply_patch` (Bug 1970574)

- src/lando/main/scm/git.py
`repo_is_initialized` is used to determine if the Git repo has
been initialized yet, or if it should be cloned. Our current
implementation of running `git status` is slow, adding about
20 minutes to the automation worker startup time before automation
jobs can be run. Switch to using `git rev-parse --is-inside-work-tree`,
which performs the same function for our purposes while being much
faster to execute.
> git: use `git rev-parse --is-inside-work-tree` to check repo initialization (Bug 1972441)

- src/lando/headless_api/tests/test_automation_api.py
Add a new `automation_job` fixture for creating automation
jobs and associated actions. This removes much of the boilerplate
around assigning the `job_id` and ordering the actions, as well
as specifying the `action_type` when it is already defined
in the `action` JSON definition.
> tests: add a fixture to create automation jobs (Bug 1973247)

- src/lando/api/tests/test_landings.py
- src/lando/conftest.py
- src/lando/headless_api/tests/test_automation_api.py
Add fixtures to mock out the `phab_trigger_repo_update` method on
the landing and automation workers. We currently add this code
snippet to many tests manually, so this fixture allows us to mock
out the call to create a new Celery job without polluting the test
with irrelevant mocks.
> tests: add fixtures to mock out `phab_trigger_repo_update` for workers (Bug 1969192)

- src/lando/ui/jinja2/stack/stack.html
At the moment the button only displays when the "Preview Landing" button
is displayed. "Preview Landing" is only displayed when the landing is
valid, which means that if a revision is closed and the user is missing
their Phabricator API key, the button will not display.
Move the "Request Uplift" button to a separate `if` block that only
checks if the user is logged in.
> stack: always display "Request Uplift" button when user is logged in (Bug 1976527)

- src/lando/utils/management/commands/maintenance.py
This is necessary as a requirements of the fix for bug 1945758. This allows us to update the worker database schemas. Without this deployments will fail as the maintenance mode is switched on, and new columns are fetched from the yet unmigrated database, leading to failures.
> utils: use raw query to pause workers for maintenance (bug 1945758)

- src/lando/api/legacy/workers/landing_worker.py
This does not change existing behavior. This just maintains compatibility with [D257609](https://phabricator.services.mozilla.com/D257609). See commit description in [D259154](https://phabricator.services.mozilla.com/D259154) and/or bug summary in [1979992](https://bugzilla.mozilla.org/show_bug.cgi?id=1979992) for a more thorough explanation.
> landing_worker: Add "--skip-android" to "./mach format" call (Bug 1979992)

- compose.yaml
Unlike the `lando` service, where we mount the whole codebase, nothing was mounted into the `proxy`.
Therefore, it could not find the staticfiles as directed by the `nginx` configuration.
> compose: mount staticfiles in nginx proxy (bug 1981857)

- src/lando/settings.py
This is necessary so the static assets for the OpenAPI doc to be generated.
> settings: add ninja to INSTALLED_APPS (bug 1980182)

- src/lando/headless_api/admin.py
- src/lando/main/admin.py
- src/lando/pushlog/admin.py
Most notably, and allow to search Jobs and Revisions by revision_id (without the 'D' prefix). Also, move users from the filter liste to the search list.
Generally, the search will allow to filter the visible columns, but there are a few handy, yet not very discoverable options:
- full-description search for Pushlog Commits,
- full-data search for HeadlessApi Automation Actions, and
- repository name search for Workers.
Some of the searches are on unindexed columns, so they may be a bit slow, but we can deal with those as we find them.
> admin: add search_fields for most pages (bug 1955972)

- src/lando/ui/legacy/forms.py
The `repository` field on the `UpliftRequestForm` currently has its
`choices` field defined as the result of the `get_uplift_repositories`
method. However the choices are set at class definition time, meaning
whatever is returned by `get_uplift_repositories` during a Lando deploy
are the choices set for every instantiation of the `UpliftRequestForm`.
If `get_uplift_repositories` doesn't return the proper results (due to
a Phabricator operational issue, network issue, etc) then the form will
have no repositories available as choices. Also, if an uplift repo is
added to Phabricator, it won't be made available until Lando is
re-deployed.
Move population of the `choices` parameter from the class definition
into `__init__` so the choices are determined when the form is
instantiated.
> forms: populate repository choices in `__init__` instead of in class definition (Bug 1985106)

- src/lando/conftest.py
When using `repo_mc` to create two test repos in one
test, creating the second repo fails because we call
`mkdir` when the `/repos` dir already exists. Add
`exists_ok=True` so multiple repos can be created in
one test.
> testing: allow `/repos` dir to exist (Bug 1989303)

- src/lando/api/legacy/uplift.py
- src/lando/ui/legacy/forms.py
Switch the `UpliftRequestForm` to query Lando's local `Repo`s
with the `approval_required=True` flag to gather the list of
valid uplift repositories. This removes an API call to Phabricator
to gather information which Lando already contains locally.
> uplift: query Lando `Repo` objects instead of Phab repo endpoint (Bug 1989305)

- src/lando/main/models/commit_map.py
- src/lando/main/tests/test_models.py
We were using `fromchangeset`, but the `json-pushes` command expects `fromchange`.
Aditionally, when catching up, some older commits in m-u may not have a `git_commit` recorded, or may not even be present in mf/f. We skip over those with a warning.
Finally, warn if no commits are known, as there are multiple cases where a `CommitMap.DoesNotExist` can be raised. This allows to differentiate them at runtime, and offers a way to fix.
> CommitMap: use correct fromchange argument to json-pushes (bug 1988682)

- src/lando/api/legacy/treestatus.py
- src/lando/api/tests/test_treestatus.py
Let is_open return false on TreeStatusCommunicationException.  That lets the landing worker defer the job instead of failing with an unhandled exception.
> treestatus: don't raise from is_open on communication error (bug 1992190)
